#!/usr/bin/env bash
# this is the story of Passwd

i="/etc/passwd"

while IFS=":" read -r USER PASS UID GID GECOS HOME COMMAND;
do
	 "The user $USER is part of the $GID gang, lives in $HOME and rides $COMMAND. $UID's place is protected by the passcode $PASS, more info about the user here: $GECOS"
done < "$i" 
