#!/usr/bin/env bash
# clock that display the 12 hours and the 59 minutes

x=0
i=1

while (( i <= 60 ));
do
    if (( i == 1 ))
    then
	echo -e "Hour: $x\n1"
    elif (( i < 60 ))
    then
	echo -e "$i"
    elif (( i == 60 ))
    then
	i-$((i-59))
    fi
    i=$((i+1))
    x=$((x+1))
done
	
