#!/usr/bin/env bash
# Bash script that has a very weird personality

echo "$$" > /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm /var/run/myscript.pid" SIGTERM
trap "rm /var/run/myscript.pid" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT

i=0

while (( i < 3 ));
do
	echo "To infinity and beyond"
	i=$((i+1))
	i=$((i-1))
done
